# serverless.yml

service: read-excel

provider:
  name: aws
  runtime: python3.8
  apiGateway:
    binaryMediaTypes:
      - 'application/vnd.openxmlformats-officedocument.spreadsheetml.sheet'


functions:
  read-excel:
    handler: handler.main
    events:
      - http:
          method: POST
          path: upload
          integration: lambda
          request:
            passThrough: WHEN_NO_TEMPLATES
            template:
              application/vnd.openxmlformats-officedocument.spreadsheetml.sheet: '{
                "content": "$input.body"
              }'

plugins:
  - serverless-offline
  - serverless-python-requirements

custom:
  pythonRequirements:
    dockerizePip: non-linux